#!/bin/bash

echo "🚀 WordPress Dokploy Quick Setup"
echo "================================"
echo ""
echo "This will configure your Dokploy deployment with default passwords."
echo "⚠️  IMPORTANT: Change these passwords for production use!"
echo ""
echo "Copy and paste the following into Dokploy's Environment Variables:"
echo ""
echo "MYSQL_ROOT_PASSWORD=ChangeMe_RootPass2024!"
echo "DB_USER=wordpress_user"
echo "DB_PASSWORD=ChangeMe_DBPass2024!"
echo "DB_NAME=wordpress_production"
echo "REDIS_PASSWORD=ChangeMe_RedisPass2024!"
echo ""
echo "Or use docker-compose.dokploy.yml which has hardcoded values for testing."
echo ""
echo "For production, run ./generate-env.sh to create secure passwords."